apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: cp4i-apic
spec:
  encryptedData:
    .dockerconfigjson: AgATyLomgol3ynNvTu6YYSjEIfJb628llCXnZHraitJQHtv9poCXsm6t7oHUcAhM5vvhztaEyzQrongvROs/D9K5oHfQwLJuzBTK/Th/3iUi51AsBsdCopULychvFDw3XJ7QySY3unV6ekjpbhPOs4LfopQlMBhLv/4eBdVR7hQDoGaG8q9ItASCF+LZ7i6X0kdal/EElMGIK6wtaC0PoTwJOMBTuOsNlcSbx8f582QSkDS2ugGl8Lyo7oUF4zvjsjBedngoJfzJgXlmxEeOWa13qO+K7Gnen87vGP9IlyDtlawXvSmx107C+gmBja0mIbhaLkQUidL7/rtl9zFryDy+jc841A9V6gtbYPyqzB1j69EqA7kLZnF1whyVWJlc+C2pjW7PmJYdgVsuOP4W48QcF4JySFA+nITy40pABP/xNgHjzv1wUKuJ6qZcq6BbO8UM21flSPbSS7csZdjsfhuOPIq+3aKtPv+DzYoWwtMl09m93Iqdw4e1kRBthVb1fbV1WwjgQNkwgVlC9qAEFA2HOcmQSxeunl9aXBLNeskYW/47iEy91U5NuvStVCaa5h/6hMA+PeVukuPo3gZQSkJNIQORN6oeHslGR+EVC7v6AX2SLcX+dKqDxQQTdbtmmzo+KyG5us37aV9XSn5bIBFcinR7aD3lwFrPOrVtTjCsb9+lmIIUvdqrEHmHdPek3F5uHVU/pVXYqgDSR2gQPmCQ/4/QV9hzs5wCWWD+0Uo0m51jLlqtaGwrGLZPV20gUbcJ8NxjoQTSgLjV+DEsxN5kA+YtUAKJFoGTL1Zrkm0xKcHp/ca00YrsfuO6MHIftpQidh8E4aqSRPN2m59SHPFg/AM+IS9hbPw172A/neajC13iAc5YvVEakOUV3x33qdINJ2Yt+xHEMJ3Q1H5zS9lnuRFt4rltOdi61wfG5wMQvsXCA0hKe/3wWm7AyAOB55rt5UZQKBG+y5lhF0uOQWwTqiBKaXjczpvlaJSHOP5eEBMt/wnpo1k8gCAj7H7QEY4GvV6Zh0qyG2h1Z7ucwf6X/licvXeOEXVaIIMUFezGvICd+PKYUmiJEP5dpscVDq2U4qXyusBEfFuyxxV95t18Xh3inpBMaY0DXt/5SPXDlKzsZ3rYPsCZrmsb6jaxtElbzyBKd6w3Ovt01oHJLcTnMVVwKqyTRlwkYhgHvCCiQFaZpSb4GSH0TnQuDvYcMh/7oSabyXM0JRUdxJWjY9jx2Zl0nhrmT5BP/X7+8HvK4OOwZorygeduu0aUiCk0SiO61WUOZi17yeMuHCzHxb7P426uOyDBILwB2jUjvNy8z016uPScNRaUBXNYUyIdFeXn
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: cp4i-apic
    type: kubernetes.io/dockerconfigjson

